[workspace]
members = [
    "kiro-audio",
    "kiro-midi",
    "kiro-time",
    "kiro-engine",
    "kiro-studio",
    "kiro-dsp",
    "kiro-synth",
]

exclude = [
    "incubator",
]

[profile.dev]
split-debuginfo = "unpacked"
